apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql2
    tier: database2
  name: mysql2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql2
      tier: database2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql2
        tier: database2
    spec:
      containers:
        - args:
            - --ignore-db-dir=lost+found
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: collegefest
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          name: mysql2
          ports:
            - containerPort: 3306
              name: mysql
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/mysql2
              name: mysql-persistent-storage2
      volumes:
        - name: mysql-persistent-storage2
          persistentVolumeClaim:
            claimName: mysql-pv-claim2
