apiVersion: v1
kind: Service
metadata:
  name: mysql2
  labels:
    app: mysql2
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app: mysql2


---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql2
  serviceName: "mysql2"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-store
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
  volumeClaimTemplates:
    - metadata:
        name: mysql-pv-claim1310
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: "manual"
        resources:
          requests:
            storage: 2Gi